### ISSUE TITLE
Callkit notification always shows video call icon

### ISSUE THREAD

**Issue by aryan88** [GetStream/stream-video-flutter#707]
I need to provide audio call support as the default, but when I try to make an audio call using the audio_rooms call type, it always shows a video call notification. I want the notification to be based on the call type, whether it is audio or video.

**Comment by TinhHuynh** [comment]
@deven98 I saw the [PR](https://github.com/GetStream/stream-video-flutter/pull/709) that fixed the issue for audio_rooms.
However, can I update a flag indicating audio/video notification with the `default` call type?
I appreciate any help you can provide.

**Comment by deven98** [comment]
@aryan88 / @TinhHuynh this is now fixed in the latest versions.

To enable/disable the video call icon, you need to set if the call type contains video on the dashboard:

![image](https://github.com/user-attachments/assets/a5333134-1d37-4eb0-bed0-a325276b33bf)

This will automatically change it on the CallKit side. Hope this helps, thanks!

**Comment by TinhHuynh** [comment]
@deven98 I used the `default` call type with video enabled, but the push notification still shows the audio call icon. Is that an issue?

<img width="936" alt="ảnh" src="https://github.com/user-attachments/assets/24e31501-78f3-417a-80a9-a7fe04e200a3">

![ảnh](https://github.com/user-attachments/assets/3128453e-8628-4fde-baae-1b75dc34760d)

```
@override
  Future<Call> makeCall(String otherMemberId, {bool isVideo = true}) async {
    ....
    final call = _callClient!
        .makeCall(callType: video.StreamCallType(), id: const Uuid().v4());
   await call.getOrCreate(
        memberIds: ids,
        ringing: true,
       ).then((value) async {
       ...
    });
   ...
  }
```

Additionally, my app's video call function supports audio and video calls, but they can turn on/off the video during the call (after both users connect the call). Suppose I set up a custom type with Video Enabled = false for audio calls on the dashboard. Does the SDK support transmitting/receiving video streams if a user opens the camera during the audio call?
